[tools]
bat = "latest"
codex = "latest"
delta = "latest"
fd = "latest"
fzf = "latest"
gemini = "latest"
gh = "latest"
jq = "latest"
lazydocker = "latest"
lazygit = "latest"
neovim = "latest"
node = "lts"
pnpm = "latest"
ripgrep = "latest"
tmux = "latest"
tokei = "latest"
uv = "latest"
